services:
  postgres:
    image: postgres:16
    container_name: pg-local
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d rhdb" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data:
