import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/app/components/clientProvider";
import {getServerSession} from "next-auth";
import {authOptions} from '@/lib/auth';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Rabbit Habit App",
    description: "Generated by create next app",
    manifest: '/manifest.json',
};

export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const session = await getServerSession(authOptions)

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ClientProvider session={session}>
                    {children}
                </ClientProvider>
            </body>
        </html>
    )
}
