import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {loadByCookie} from "@/app/auth/login/actions";
import ClientProvider from "@/app/components/clientProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    manifest: '/manifest.json',
};

export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const uid = await loadByCookie()

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ClientProvider uid={uid}>
                    {children}
                </ClientProvider>
            </body>
        </html>
    )
}